language: php

php:
    - 5.3.3
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7
    - hhvm

before_script:
    - composer install --dev --prefer-source
    - bin/console doctrine:database:create
    - bin/console doctrine:schema:load
    - bin/console fixture:load
